version: '3.8'

services:

  ghost:
    image: ghost:5.64.0
    networks:
      - ghostcms
      - public
    volumes:
      - content:/var/lib/ghost/content
    restart: on-failure
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MARIADB_USER:-ghost}
      database__connection__port: 3306
      database__connection__password: ${MARIADB_PASSWORD:-ghost_password}
      database__connection__database: ${MARIADB_DATABASE:-ghost_cms}
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__host: smtp.eu.mailgun.org
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: ${MAILGUN_USER:-}
      mail__options__auth__pass: ${MAILGUN_PASSWORD:-}
      mail__from: "DevOps Diaries <info@roshamagin.site>"
      url: https://roshamagin.site
      admin__redirects: 'true'
      NODE_ENV: production
    ports:
      - '2368:2368'
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.tls=true
      - traefik.http.routers.ghost.rule=Host(`roshamagin.site`)
      - traefik.http.routers.ghost.entrypoints=websecure
      - traefik.http.routers.ghost.tls.certresolver=myresolver
      - traefik.http.services.ghost.loadbalancer.server.port=2368
    depends_on: [ db ]

  db:
    image: mariadb:11.1.2
    restart: always
    networks: [ ghostcms ]
    environment:
#      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_ROOT_HOST: "localhost"
      MARIADB_DATABASE: ${MARIADB_DATABASE:-ghost_cms}
      MARIADB_USER: ${MARIADB_USER:-ghost}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-ghost_password}
    volumes:
      - db:/var/lib/mysq
networks:
  public:
    external: true
  ghostcms:
    attachable: false

volumes:
  content:
    driver: local
  db:
    driver: local
