version: '3.8'

services:

  ghost:
    image: ghost:latest
    networks:
      - galera_galera-network
      - public
    volumes:
      - content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: proxysql
#      database__connection__host: mariadb-galera-1
      database__connection__user: ghost
      database__connection__port: 6033
#      database__connection__port: 3306
      database__connection__password: ghost_password
      database__connection__database: ghost_cms
      url: https://roshamagin.site
      NODE_ENV: production
    deploy:
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.ghost.tls=true
        - traefik.http.routers.ghost.rule=Host(`roshamagin.site`) || Host(`www.roshamagin.site`)
        - traefik.http.routers.ghost.entrypoints=websecure
        - traefik.http.routers.ghost.tls.certresolver=myresolver
        - traefik.http.services.ghost.loadbalancer.server.port=2368

networks:
  public:
    external: true
  galera_galera-network:
    external: true

volumes:
  content:
    driver: local