version: '3.8'

services:

  ghost:
    image: ghcr.io/romaxa55/ghost-cms-in-docker:master
    networks:
      - galera_galera-network
      - public
    environment:
      database__client: mysql
      database__connection__host: proxysql
      database__connection__user: ghost_cms
      database__connection__password: ghost_password
      database__connection__database: ghost_cms
      url: https://roshamagin.site
      NODE_ENV: production
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.ghost.tls=true
        - traefik.http.routers.ghost.rule=Host(`roshamagin.site`) && Host(`www.roshamagin.site`)
        - traefik.http.routers.ghost.entrypoints=websecure
        - traefik.http.routers.ghost.tls.certresolver=myresolver
        - traefik.http.services.ghost.loadbalancer.server.port=2368


networks:
  public:
    external: true
  galera_galera-network:
    external: true