- name: Install haproxy
  hosts: haproxy
  gather_facts: true
  roles:
    - role: haproxy
      vars:
        haproxy_domain: roshamagin.site
        haproxy_version: 2.7.8
        workers:
          - name: "worker1"
            address: "{{ hostvars['worker1'].ip }}"
            port: 32443
          - name: "worker2"
            address: "{{ hostvars['worker2'].ip }}"
            port: 32443