apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-claim-1
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghost-cms-storage
  hostPath:
    path: /opt/postgresql/data1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-claim-2
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghost-cms-storage
  hostPath:
    path: /opt/postgresql/data2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-claim-3
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghost-cms-storage
  hostPath:
    path: /opt/postgresql/data3
