---
- name: Converge
  hosts: all
  become: true

  vars:
    haproxy_socket: ''
    haproxy_chroot: ''
    haproxy_user: root
    haproxy_group: root

    haproxy_backend_servers:
      - name: app1
        address: 127.0.0.1:8080

  roles:
    - role: haproxy
