---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: haproxy1
    pre_build_image: true
    image: mrlesmithjr/debian:11
    privileged: true
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    docker_networks:
      - name: 'galera_network'
        ipam_config:
          - subnet: '192.168.10.0/24'
    networks:
      - name: "galera_network"
        ipv4_address: '192.168.10.20'
    cgroupns_mode: host
    command: /lib/systemd/systemd
    groups:
      - nginx
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
